### ISSUE TITLE
Walkoff Error

### ISSUE THREAD

**Issue by DaniAntSinc** [MangoTux/baseball-sim#1]
In a walk-off situation, the inning will still play out. 

For example - Ragamuffins and Scalliwags were in the 11th. With 1 out in the bottom of the 11th, the Scalliwags hit a homerun to 'end the game' but the two remaining people struck out to end the inning before the game was over. 

![image](https://user-images.githubusercontent.com/8687354/56586328-236f0b80-65a5-11e9-9b12-be161095af2e.png)

![image](https://user-images.githubusercontent.com/8687354/56586338-2a961980-65a5-11e9-9c71-686dd249d477.png)

**Comment by MangoTux** [comment]
Fixed with commit [f59fb081717e3e74254d9d0cb0d66389a35093e7](https://github.com/MangoTux/baseball-sim/commit/f59fb081717e3e74254d9d0cb0d66389a35093e7)
